### PR TITLE
Incorporate error details in error when csev command fails

### LINKED ISSUE #45: Improve potentially confusing `config-server-encrypt-value` error response
Using plugin version 1.0.2 against SCS 2.0. If a `p-config-server` service instance has been created without an `encrypt` configuration parameter then trying to use `cf config-server-encrypt-value` against it results in an error output that is confusing (IMHO):
```
[Georges-MBP master]: cf config-server-encrypt-value simple-git-service "hello"
FAILED
Authenticated post to 'https://config-d86b7544-5263-4cb5-814f-dbf96b9a2b4c.apps.black.springapps.io/encrypt' failed: 404 Not Found
```
The `404 Not Found` suggests that the `/encrypt` endpoint does not exist when in reality it is available as normal. Looking at the detailed HTTP response from the `p-config-server` backing app it looks like the `404` refers to the missing encryption key. This is based on the HTTP POST response from the SI backing app containing a `404` status code plus the following response body:
```
{"description":"No key was installed for encryption service","status":"NO_KEY"}
```

### PR DESCRIPTION
**Pull request by georgeharley**
* If HTTP response is not OK but contains body then use that body in the error returned to the user
* this resolves #45

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -28,3 +28,4 @@ _testmain.go
 
 # Coverage reports
 *.coverprofile
+.idea
```
Comment (glyn) [inline .gitignore]: This is ok, but I opted out of that game permanently by creating a `~/.gitignore_global` containing:
```
*~
.DS_Store
.idea
*.iml
\#*#
*.hsp
*.sav
*.scpt
```
I don't see why individual projects should necessarily support IntelliJ but not other IDEs. Please decide for yourself - this is just a suggestion.

File: httpclient/authclient_test.go [hunk 2]
```diff
@@ -268,8 +268,25 @@ var _ = Describe("Authclient", func() {
...
 			})
 
-			It("should return the error", func() {
+			It("should return the error with no body content", func() {
 				Expect(err).To(MatchError("Authenticated post to 'https://eureka.pivotal.io/auth/request' failed: 404 Not found"))
+				Expect(respBody).To(BeNil())
+			})
+
+			Context("when the bad status response contains a body", func() {
+
```
Comment (glyn) [inline httpclient/authclient_test.go]: Extraneous blank line.

**Comment by georgeharley** [comment]
Many thanks for the feedback @glyn I've updated the commit now to incorporate those suggestions.

**Comment by vanjan** [comment]
Any chance we can get this released?
